apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: icappn7ee-go
  janus-idp.io/tekton: icappn7ee-go
  backstage.io/kubernetes-id: icappn7ee-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: icappn7ee-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
